### Base routes

// Get base route
GET http://localhost:{{$dotenv PORT}}/

###

// Health check
GET http://localhost:{{$dotenv PORT}}/healthcheck

###

// Get new TTNMapper data

POST http://localhost:{{$dotenv PORT}}/fetch_device_data HTTP/1.1

### TTN Mapper Datapoints

// Get all tnnmapper_datapoints
GET http://localhost:{{$dotenv PORT}}/ttnmapper_datapoints

### Devices

// Get all devices
GET http://localhost:{{$dotenv PORT}}/devices

###

// Add a device subscription

POST http://localhost:{{$dotenv PORT}}/devices HTTP/1.1
Content-Type: application/json

{
    "deviceId": "loris-hfu-001",
    "subscription": true
}

###

// Get data from specific device from ttnmapper

GET http://localhost:{{$dotenv PORT}}/devices/ttnmapper_api/loris-hfu-001

### Device GPS Datapoints

// Get all device gps datapoints

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints

###

// Get all device gps datapoints with 3 or more ttnmapper datapoints

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints?min_ttnmapper_datapoints=3

###

// Get all device gps datapoints with 3 or more ttnmapper datapoints and a max hdop of 2

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints?min_ttnmapper_datapoints=3&max_hdop=2

###

// Get all ttnmapper datapoints for a specific device

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints/43/ttnmapper_datapoints_with_gateway_locations

### Gateways

// Get all gateways
GET http://localhost:{{$dotenv PORT}}/gateways

###

// Get GPS Datapoints for specific gateway

GET http://localhost:{{$dotenv PORT}}/gateways/eui-ac1f09fffe06048e/gps_datapoints_with_rssi
