// Get base route
GET http://localhost:{{$dotenv PORT}}/

### TTN Mapper Datapoints

// Get all tnnmapper_datapoints
GET http://localhost:{{$dotenv PORT}}/ttnmapper_datapoints

### Device Subscriptions

// Get all device subscriptions
GET http://localhost:{{$dotenv PORT}}/device_subscriptions

###

// Add a device subscription

POST http://localhost:{{$dotenv PORT}}/device_subscriptions HTTP/1.1
content-type: application/json

{
    "deviceId": "elv-long-boi"
}

### Devices

// Get all devices
GET http://localhost:{{$dotenv PORT}}/devices

###

// Get data from specific device from ttnmapper

GET http://localhost:{{$dotenv PORT}}/devices/ttnmapper_api/loris-hfu-001

### Device GPS Datapoints

// Get all device gps datapoints

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints

###

// Get all device gps datapoints with 3 or more ttnmapper datapoints

GET http://localhost:{{$dotenv PORT}}/device_gps_datapoints?min_ttnmapper_datapoints=3
