version: "3"
services:
    ttnmapper-reader:
        build: ./ttnmapper-reader
        restart: always
        ports:
            # Backend API
            - "3000:3000"
        depends_on:
            - db
            - rabbitmq
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttn-locator
        restart: always
        ports:
            # PostgreSQL Port
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin4_container
        depends_on:
            - db
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            # Web Interface
            - "80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            # AMQP
            - 5672:5672
            # Management Web Interface
            - 15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
    postgres-data:
    pgadmin-data:
