---
version: '3.9'
services:
    test-db:
        restart: always
        image: postgis/postgis:15-3.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttn-locator-backend_TEST
        ports:
            - '57110:5432'
        networks:
            - test-network

networks:
    test-network:
        driver: bridge
