version: "3"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttn-locator
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin4_container
        depends_on:
            - db
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
volumes:
    postgres-data:
    pgadmin-data:
