---
version: "3"
services:
    db:
        extends:
            file: ./docker-compose.yml
            service: db
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/ttnmapper-reader
