---
version: "3"
services:
    ttnmapper-reader:
        image: ghcr.io/bassadin/ttnmapper-reader:latest
        build: .
        restart: always
        links:
            - db
        ports:
            - "${PORT}:${PORT}"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/ttnmapper-reader
            # The healthcheck needs this to be set
            - PORT=3000
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttnmapper-reader
        restart: always
        ports:
            # PostgreSQL Port
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin4_container
        links:
            - db
        image: dpage/pgadmin4:7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            # Web Interface
            - "57000:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./pgadmin_server_config/servers.json:/pgadmin4/servers.json
            - ./pgadmin_server_config/pgpass:/pgpass:rw
    ttn-locator-frontend:
        image: ghcr.io/bassadin/ttn-locator-frontend:latest
        restart: unless-stopped
        links:
            - ttnmapper-reader
        ports:
            - '8080:80'
        environment:
            - VITE_TTNMAPPER_LOCATOR_API_URL=http://ttnmapper-reader:3000
volumes:
    postgres-data:
    pgadmin-data:
