---
version: "3"
services:
    ttnmapper-reader:
        build: .
        restart: always
        depends_on:
            - db
        ports:
            - "${PORT}:${PORT}"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/ttnmapper-reader
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttnmapper-reader
        restart: always
        ports:
            # PostgreSQL Port
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin4_container
        depends_on:
            - db
        image: dpage/pgadmin4:7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            # Web Interface
            - "57000:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./pgadmin_server_config/servers.json:/pgadmin4/servers.json
            - ./pgadmin_server_config/pgpass:/pgpass:rw
volumes:
    postgres-data:
    pgadmin-data:
