# .github/workflows/test.yaml
name: test

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ttnmapper-reader
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: pnpm install
              run: pnpm install --frozen-lockfile
            - name: pnpm build
              run: pnpm run build

            - name: pnpm prisma generate
              run: npx prisma migrate deploy
            - name: Prisma seed
              run: pnpm run seed
